export const ckEditorConfig = {
  placeholder: false,
  title: false,
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      "link",
      "|",
      "bulletedList",
      "numberedList",
      "|",
      "alignment",
      "outdent",
      "indent",
      "|",
      "undo",
      "redo",
      "blockQuote",
      "fontBackgroundColor",
      "fontColor",
      "fontFamily",
      "highlight",
      "fontSize",
    ],
  },
  language: "en",
  removePlugins: ["Title"],
};
